### PR TITLE
 [Fix][#14] Demo app: when switching between medias the app crashes

### LINKED ISSUE #14: Demo app: when switching between medias the app crashes
## Expected Behavior
The user switches between tab to see different medias, it should switch successfully without crashes

## Current Behavior
Xcode reports a crash in `Slider(value: $viewModel.currentElapsedTime, in: .zero...viewModel.mediaTotalTime) {` because the `viewModel.mediaTotalTime` seems to be less or equal than `.zero`

## Possible Solution
Check value before rendering the slider or fallback to a default value

## Steps to Reproduce
1. Build app
2. Switch media types
3. See crash

## Context (Environment)
`main` branch

### PR DESCRIPTION
**Pull request by KarenBaliero**
## Description

Xcode reports a crash in Slider(value: $viewModel.currentElapsedTime, in: .zero...viewModel.mediaTotalTime) { because the viewModel.mediaTotalTime seems to be less or equal than .zero

## Solution

Just changed the default value of initial, minimum and maximum to `.zero` so it works when the media hasn't loaded yet

Tried to make the controls disabled but they already are disable, even if the UI doesn't change, so set it as disabled appeared weird. 

## Related Issues

- Closes #14

## How to test it

Open simulator and switch between different media.

## Visual reference

Screenshot of bug fix

### CODE REVIEW

File: Sources/EnhancedMediaPlayer/MediaPlayerView.swift [hunk 1]
```diff
@@ -64,7 +64,11 @@ extension MediaPlayerView {
         }
 
         var mediaTotalTime: Double {
-            player.currentItem?.duration.seconds ?? Constants.fallbackTotalDuration
+            let duration = player.currentItem?.duration.seconds ?? Constants.fallbackDuration
+            if duration.isNaN {
+                return Constants.fallbackDuration
+            }
+            return duration
```
Comment (vitorjmoriya) [inline Sources/EnhancedMediaPlayer/MediaPlayerView.swift:71]:
```suggestion swift
            guard let duration = player.currentItem?.duration.seconds, !duration.isNaN else {
                return Constants.fallbackDuration
            }
            return duration

**Review by andrepapoti — APPROVED** [review]
lgtm
